version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Use any base image you need for your project
    working_directory: ~/repo  # Working directory for the code

jobs:
  build_and_push:
    executor: docker-executor
    steps:
      # Step 1: Check out the code from GitHub repository
      - checkout
      
      # Step 2: Set up Docker for building the images
      - setup_remote_docker:
          docker_layer_caching: true  # Enable layer caching to speed up builds

      # Step 3: Build and push Docker images for each of the 4 images
      - run:
          name: Build and push udagram-frontend
          command: |
            docker build -t $DOCKER_USERNAME/udagram-frontend:$CIRCLE_SHA1 ./udagram-frontend
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/udagram-frontend:$CIRCLE_SHA1

      - run:
          name: Build and push udagram-api-feed
          command: |
            docker build -t $DOCKER_USERNAME/udagram-api-feed:$CIRCLE_SHA1 ./udagram-api-feed
            docker push $DOCKER_USERNAME/udagram-api-feed:$CIRCLE_SHA1

      - run:
          name: Build and push udagram-api-user
          command: |
            docker build -t $DOCKER_USERNAME/udagram-api-user:$CIRCLE_SHA1 ./udagram-api-user
            docker push $DOCKER_USERNAME/udagram-api-user:$CIRCLE_SHA1

      - run:
          name: Build and push udagram-reverseproxy
          command: |
            docker build -t $DOCKER_USERNAME/udagram-reverseproxy:$CIRCLE_SHA1 ./udagram-reverseproxy
            docker push $DOCKER_USERNAME/udagram-reverseproxy:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_push_images:
    jobs:
      - build_and_push:
          context:
            - ContextForDockerHub  # Correct indentation here